version: '3'

services:
  app:
    image: dify-php
    volumes:
      - .:/app
    working_dir: /app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis
    entrypoint: []
    command: tail -f /dev/null

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    ports:
      - "6380:6379"

volumes:
  redis_data: